Reviewed the documentation for STAR
Unity-Technologies/com.unity.mobile.logcat pull request #154
Opened 2022-04-06 09:33 UTC by JordanL8

### Purpose of PR
Changed structure to adhere to our templates and reviewed content to adhere to our style guide.

2022-04-06 10:08 UTC, todi1856 commented on com.unity.mobile.android-logcat/Documentation~/android-logcat-window-reference.md
> +| **Tools**            | A drop-down list of tools that can help you to debug your Android application. The options are:**Screen Capture**: Captures screenshots and videos of the connected Android de
"Captures screenshots and videos of the connected Android device." shouldn't be
"Captures screenshots and videos from the connected Android device." ?

2022-04-06 10:08 UTC, todi1856 commented on com.unity.mobile.android-logcat/Documentation~/screen-capture-window-reference.md
> +![](images/capture_screenshot.png)
In previous image, I saw you included A,B,C icons, but here capture_screenshot doesn't have icons inside of image, is that on purpose? https://docs-internal-preview.prd.it.unity3d.com/lewis/logcat-star/manual/screen-capture-window-reference.html

2022-04-06 10:08 UTC, todi1856 commented on com.unity.mobile.android-logcat/Documentation~/memory-window-reference.md
> +
Could you please include https://docs.unity3d.com/Packages/com.unity.mobile.android-logcat@1.2/manual/images/MemoryDump.png since it's a good source of reference

2022-04-06 10:08 UTC, todi1856 commented on com.unity.mobile.android-logcat/Documentation~/memory-window.md
> +| [Memory window reference](memory-window-reference.md) | Understand the Memory window interface. |
It seems the info:
"If you allocate memory using native functions malloc, new or using C# Marshal.AllocHGlobal, such memory will appear in Heap Alloc and Heap Size groups under Native Heap type.
If you allocate memory using java functions like new, such memory will appear in Heap Alloc and Heap Size groups under Java Heap type.
In both cases above both native and java memory won't appear in PSS group until you'll try to write or read from allocated native or java memory.
If you allocate memory using C# new function such memory will appear under PSS group Private Other memory type.
"
was removed. Are you planning of bringing it back?

2022-04-06 14:44 UTC, JordanL8 commented on com.unity.mobile.android-logcat/Documentation~/screen-capture-window-reference.md
> +![](images/capture_screenshot.png)
I've annotated the dark theme screenshot you provided with the labels

2022-04-06 15:23 UTC, JordanL8 commented on com.unity.mobile.android-logcat/Documentation~/memory-window.md
> +| [Memory window reference](memory-window-reference.md) | Understand the Memory window interface. |
Ah yes I've added it to the memory window reference page now.

2022-04-06 15:29 UTC, JordanL8 commented on com.unity.mobile.android-logcat/Documentation~/memory-window-reference.md
> +
Ah yeah I added a comment about whether this was useful. I'll add it back

2022-04-07 16:39 UTC, JordanL8 commented on com.unity.mobile.android-logcat/Documentation~/view-messages.md
> +There can be multiple Unity applications on a connected Android device. The [Android Logcat window](android-logcat-window.md) can display messages from:
Fixed

2022-04-07 16:39 UTC, JordanL8 commented on com.unity.mobile.android-logcat/Documentation~/view-messages.md
> +    * The application for the top [activity](https://developer.android.com/guide/components/activities/intro-activities) currently running on the selected device.
Fixed

2022-04-07 16:41 UTC, JordanL8 commented on com.unity.mobile.android-logcat/Documentation~/android-logcat-window-reference.md
> +| **Tools**            | A drop-down list of tools that can help you to debug your Android application. The options are:**Screen Capture**: Captures screenshots and videos of the connected Android de
Ah the line breaks didn't copy over. Fixed that and the wording

2022-04-07 17:55 UTC, todi1856 requested changes

2022-04-08 09:28 UTC, JordanL8 commented on com.unity.mobile.android-logcat/Documentation~/stacktrace-utility-set-up.md
> +4. Find the `libmain`, `libunity`, and `libil2cpp` symbol files and add all of them. Different versions of Unity produce these symbol files in different locations. For information on where to find th
I can indeed, fixed

2022-04-08 09:28 UTC, JordanL8 commented on com.unity.mobile.android-logcat/Documentation~/android-logcat-window-reference.md
> +| **Reconnect**        | Reconnects the Android Logcat window to the                  |
Fixed

2022-04-11 11:00 UTC, todi1856 approved these changes

2022-04-11 11:21 UTC, merged