Introduce a way to inject inputs via logcat package
Unity-Technologies/com.unity.mobile.logcat pull request #168
Opened 2023-06-13 10:18 UTC by todi1856

## **Please read and consider what information you want to pass on to people reviewing this PR**

### Purpose of PR
**Type of change:**
- [ ] Bug fix
- [X] Improvement
- [ ] Code refactor
- [ ] Breaking change
- [ ] Documentation update
- [ ] Other (please describe) 

* **Description of the feature**
Provides UI for injecting key events/send text to android device
* **Links to screenshots, design docs, user docs, etc.**
![InputsWindow](https://github.com/Unity-Technologies/com.unity.mobile.logcat/assets/568752/86a7679a-031a-4dc5-8cae-f52db8e87dc7)

* **Links to Jira/Fogbugz cases**
* **Halo effect**
None
* **Performance Impact**
None
* **Package requirements**
2020.3+

### Checklist for PR maker
- [ ] Have you added a backport label? (if needed)
- [X] Have you updated the Changelog? _Each package has a `CHANGELOG.md` file_
- [X] **Have you added or updated the Documentation to your PR?** _When you add a new feature, change a property name, or change the behaviour of a feature, it's best practice to include related documentation changes in the same PR_
---
### Testing status
* **Existing or new automation tests - what automation was added, changed**
None
* **Detailed description of what testing was done, what projects were run**
I used this project https://github.com/Unity-Technologies/com.unity.mobile.logcat/tree/inputs/TestProjects/InputTests
And tried to send various keys + text to running application
* **What environment did you test on?**
Windows + Google Pixel 2 Android 11
* **Projects**
_Any existing projects ready for testing should be noted here_
* **Testing checklist**
- [ ] Built and run editor Locally or Katana
- [ ] Built a player Android/iOS (if applicable)
- [ ] Run on device Android/iOS (if applicable)
- [ ] If new feature has UI, does it match Unity style? (Unity [HIG](https://unitytech.github.io/unityeditor-hig/)?)
- [ ] Tested Undo/Redo + Prefab overrides + Alignment in Preset
- [ ] All items have tooltips?
---
### Note to guardian
_Changeset to use, if extra changesets on top. Any other notes to pass along_

### Comments to reviewers
_Notes for the reviewers you have assigned_

2023-06-28 09:52 UTC, aurimasc approved these changes

2023-06-28 09:52 UTC, aurimasc commented on com.unity.mobile.android-logcat/Editor/AndroidLogcatDevice.cs
> +                        formattedLine = formattedLine.Replace("\"", "\\\"");
Escaping quotes here? Maybe escape backslashes as well in case someone tries to send \" as input?

2023-07-03 14:56 UTC, IGuscin approved these changes
Few small issues:

- Quotes are not escaped correctly
'path:"C:\program files\Test\"' - doesn't print anything.
- Send text doesn't work with diacritics
ĄČĘ.. are not sent as input
- Kill with signal - some signals doesn't produce anything in logs (SIGALRM, SIGTERM, SIGNONE, SIGINT..) and some doesn't kill app at all (SIGHUP, SIGQUIT)
- Mute button works a bit strange. In app it does nothing until another key is sent (like mute after brightness up works fine)
- Not sure if PR related, but Package name in Tag is truncated. Package Name com.DefaultCompany.InputTests in tag is shown as pany.InputTests
- Block controlling app (Start, Force Stop, Crash..) has unneeded :. Package**:** Name:

Other than that - very nice improvement to the Logcat package. Thank you!

2023-07-10 06:50 UTC, IGuscin requested changes
More issues related to the PR encountered:

- Pressing Alt from Keyboard keys with GA as app entry point collapses input field
- Most buttons from the numpad doesn’t work. All the numbers do nothing, While /*=-+, and enter works fine
- Text keys are barely usable: no way to select text using logcat package
- Send text resizes entire logcat UI to accommodate text supplied, breaking UI.
- Long text is truncated at some point leading to a data loss. Try sending couple paragraphs of lorem ipsum and notice each paragraph missing some part.

More details can be found in testing document: 
https://docs.google.com/document/d/1O1CTyRbmen7O9tQuTt3eYVvKjhLChRXIu7XooYIvdAA/edit

2023-07-11 14:36 UTC, todi1856 commented on com.unity.mobile.android-logcat/Editor/AndroidLogcatDevice.cs
> +                        formattedLine = formattedLine.Replace("\"", "\\\"");
backslashes seems to be sent correctly. but Ilja's string
'path:"C:\program files\Test"'  was not sent correctly, fixed that

2023-07-11 14:38 UTC, aurimasc commented on com.unity.mobile.android-logcat/Editor/AndroidLogcatDevice.cs
> +                                new KeyValuePair<string, string>("\"", "\\\"")
What about escaping backslashes?

2023-07-11 15:07 UTC, todi1856 commented on com.unity.mobile.android-logcat/Editor/AndroidLogcatDevice.cs
> +                                new KeyValuePair<string, string>("\"", "\\\"")
That's not needed as far as I can see, backslashes are correctly received by android
For example, this string
```
'path:"C:\program files\Test"' 
```

is sent like this:
```
adb -s 711KPQJ0939020 shell input text ''\''path:\"C:\program files\Test\"'\'' '
```

and is correctly received by Android

2023-07-11 16:07 UTC, aurimasc commented on com.unity.mobile.android-logcat/Editor/AndroidLogcatDevice.cs
> +                                new KeyValuePair<string, string>("\"", "\\\"")
Try two backslashes one after another. It seems in POSIX shell backslash expands to itself unless is followed by $, ` or another backslash.

2023-07-12 08:08 UTC, todi1856 commented on com.unity.mobile.android-logcat/Editor/AndroidLogcatDevice.cs
> +                                new KeyValuePair<string, string>("\"", "\\\"")
```
adb -s 711KPQJ0939020 shell input text '//test//'
```

produces

```
//test//
```

text on Android, which is weird a bit, but that's how it is.

2023-07-13 07:57 UTC, IGuscin approved these changes
Major issues are now fixed. Some of the reported are coming from GameActivity or expected Android behavior, having nothing related with the PR.
Nice job, Tomas. Very useful improvement

2023-07-13 08:17 UTC, merged