add android logcat settings docs
Unity-Technologies/com.unity.mobile.logcat pull request #176
Opened 2023-10-16 11:49 UTC by anjalin14

## **Please read and consider what information you want to pass on to people reviewing this PR**

### Purpose of PR
**Type of change:**
- [ ] Documentation update

* **Description of the feature**
_What it does, why was it created, how does it work and so on..._
* **Links to screenshots, design docs, user docs, etc.**
* **Links to Jira/Fogbugz cases**
* **Halo effect**
_What areas do you know/expect this feature to affect? Do you have any worries about possible breaking points? Write them down here._
* **Performance Impact**
_Could this PR affect performance? If so, what has been done to measure time taken per frame, memory used, etc.?_
* **Package requirements**
_What Unity Editor version is required/supported? Any other dependancy packages needed?_

### Checklist for PR maker
- [ ] Have you added a backport label? (if needed)
- [ ] Have you updated the Changelog? _Each package has a `CHANGELOG.md` file_
- [ ] **Have you added or updated the Documentation to your PR?** _When you add a new feature, change a property name, or change the behaviour of a feature, it's best practice to include related documentation changes in the same PR_
---
### Testing status
* **Existing or new automation tests - what automation was added, changed**
_Put any relevant Yamato links here_
* **Detailed description of what testing was done, what projects were run**
_Tell the reviewers what did you already test, so that they may have a better understanding when reviewing/testing this PR themselves_
* **What environment did you test on?**
_Your Operating System, Platforms you ran on, Graphics APIs and any other relevant info you can think of_
* **Projects**
_Any existing projects ready for testing should be noted here_
* **Testing checklist**
- [ ] Built and run editor Locally or Katana
- [ ] Built a player Android/iOS (if applicable)
- [ ] Run on device Android/iOS (if applicable)
- [ ] If new feature has UI, does it match Unity style? (Unity [HIG](https://unitytech.github.io/unityeditor-hig/)?)
- [ ] Tested Undo/Redo + Prefab overrides + Alignment in Preset
- [ ] All items have tooltips?
---
### Note to guardian
_Changeset to use, if extra changesets on top. Any other notes to pass along_

### Comments to reviewers
_Notes for the reviewers you have assigned_

2023-10-16 13:10 UTC, todi1856 requested changes
Few questions

2023-10-16 13:10 UTC, todi1856 commented on com.unity.mobile.android-logcat/Documentation~/TableOfContents.md
> +* [Android Logcat Settings](android-logcat-settings)
Shouldn't it be (android-logcat-settings.md)

2023-10-16 13:10 UTC, todi1856 commented on com.unity.mobile.android-logcat/Documentation~/android-logcat-settings.md
> +> Messages
what does this tag do ? It looks a bit weird when looking via https://github.com/Unity-Technologies/com.unity.mobile.logcat/blob/docr-3561/com.unity.mobile.android-logcat/Documentation~/android-logcat-settings.md in github website

2023-10-16 13:32 UTC, anjalin14 commented on com.unity.mobile.android-logcat/Documentation~/TableOfContents.md
> +* [Android Logcat Settings](android-logcat-settings)
yes

2023-10-16 13:33 UTC, anjalin14 commented on com.unity.mobile.android-logcat/Documentation~/android-logcat-settings.md
> +> Messages
It is for displaying the name of the image file. I added it after comparing with the existing ones.

2023-10-17 08:42 UTC, todi1856 approved these changes

2023-10-17 08:42 UTC, merged

2023-10-18 15:32 UTC, kilroyandrew commented on com.unity.mobile.android-logcat/Documentation~/android-logcat-settings.md
> +the color picker interface, you can use slider or text box to set your preferred RGB or Hexadecimal color code. Alternatively, you can set the color you prefer using the **Swatches** option at the bo
Just to flag there's a double `the` at the end of line 36 and start of 37.